[[language]]
name = "rust"
language-servers = ["rust-analyzer" ]
formatter = { command = "rustfmt" }
auto-format = true
indent = { tab-width = 4, unit = "t" }
[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "c"
language-servers =  ["clangd"]
auto-format = true
formatter = { command = "clang-format-12", args = ["-style=file"] }
indent = { tab-width = 4, unit = "t" }

[[language]]
name = "cpp"
language-servers =  ["clangd"]
auto-format = false
indent = { tab-width = 4, unit = "t" }
formatter = { command = "clang-format-12", args = ["-style=file"] }
comment-token = "//"
[language-server.clangd]
command = "clangd"
args=["--compile-commands-dir=./build_bundle_cpp"] 

[[language]]
name = "bash"
language-servers = ["bash-language-server"]
formatter = { command = "shfmt" , args = ["-l","-w"]}
auto-format = true
[language-server.bash-language-server]
command = "bash-language-server"

[[language]]
name = "python"
language-servers = [ "pylsp", "ruff-lsp" ]
auto-format = true

[language.formatter]
command="ruff"
args=["format","-","-q"]
lineLength = 80

[language-server.ruff-lsp]
command = "ruff-lsp"
[language-server.pylsp.plugins]
pyflakes = {enabled = false}
mccabe = {enabled = false}
pyls_isort = {enabled = false}
pycodestyle = {enabled = false, maxLineLength = 88}
pydocstyle = {enabled = false}
autopep8 = {enabled = false}
yapf = {enabled = false}
flake8 = {enabled = false}
pylint = {enabled = false}
ruff = {enabled = true, extendSelect = ["I"]}
mypy = {enabled = true, live_mode = true, strict = true}
