# theme = "darcula" 
theme = "solarized_light" 

[editor]
line-number = "relative"
cursorline = true
mouse = false
bufferline = "multiple"
true-color = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-a = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-q = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# duplicate line up
C-A-a = ["extend_line","yank","open_above","normal_mode","replace_with_yanked", "insert_mode"]
# duplicate line down
C-A-q = ["extend_line","yank","move_line_down","open_above","normal_mode","replace_with_yanked", "insert_mode"]
# disabling arrow keys
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
# yazi picker
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"

[keys.insert]
# move line up
A-a = ["extend_line","yank","move_line_up","open_above","replace_with_yanked","move_line_down", "move_line_down", "extend_line", "delete_selection", "move_line_up", "move_line_up"]
# move line down
A-q = ["extend_line","delete_selection", "paste_after", "move_line_down"]
# duplicate line up
C-A-a = ["extend_line","yank","open_above","normal_mode","replace_with_yanked", "insert_mode"]
# duplicate line down
C-A-q = ["extend_line","yank","move_line_down","open_above","normal_mode","replace_with_yanked", "insert_mode"]
# disabling arrow keys
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

# [keys.normal.m]
# w = ["select_textobject_around", "Word"]
# W = ["select_textobject_around", "WORD"]
# f = ["select_textobject_around", "Function"]

[editor.cursor-shape]
insert = "bar"
