theme = "darcula" 

[editor]
line-number = "relative"
cursorline = true
mouse = false
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-s = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-z = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# duplicate line up
C-A-z = ["extend_line","yank","open_above","normal_mode","replace_with_yanked", "insert_mode"]
# duplicate line down
C-A-s = ["extend_line","yank","move_line_down","open_above","normal_mode","replace_with_yanked", "insert_mode"]

[keys.insert]
# move line up
A-z = ["extend_line","yank","move_line_up","open_above","replace_with_yanked","move_line_down", "move_line_down", "extend_line", "delete_selection", "move_line_up", "move_line_up"]
# move line down
A-s = ["extend_line","delete_selection", "paste_after", "move_line_down"]
# duplicate line up
C-A-z = ["extend_line","yank","open_above","normal_mode","replace_with_yanked", "insert_mode"]
# duplicate line down
C-A-s = ["extend_line","yank","move_line_down","open_above","normal_mode","replace_with_yanked", "insert_mode"]

# [keys.normal.m]
# w = ["select_textobject_around", "Word"]
# W = ["select_textobject_around", "WORD"]
# f = ["select_textobject_around", "Function"]

[editor.cursor-shape]
insert = "bar"
