[[language]]
name = "rust"
language-server = { command = "rust-analyzer"}
formatter = { command = "rustfmt" }
auto-format = true
[language.config]
checkOnSave = { command = "clippy" }
indent = { tab-width = 4, unit = "t" }

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"
[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"
[language.debugger.templates.args]
program = "{0}"
runInTerminal = true


[[language]]
name = "c"
# language-server = {command = "clangd-12"}
language-server = { command = "clangd-12", args=["--compile-commands-dir=*/build/"] }
auto-format = true
formatter = { command = "clang-format", args = ["-style=file:.clang-format"] }
indent = { tab-width = 4, unit = "t" }

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"
[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"
[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[[language]]
name = "cpp"
language-server = {command = "clangd"}
auto-format = true

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"
[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"
[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[[language]]
name = "bash"
language-server = { command = "bash-language-server"}
formatter = { command = "shfmt" , args = ["-l","-w"]}
auto-format = true

[[language]]
name = "python"
language-server = { command = "pylsp"}
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[language.config.pylsp.plugins]
pyflakes = {enabled = false}
mccabe = {enabled = false}
pyls_isort = {enabled = false}
pycodestyle = {enabled = false, maxLineLength = 88}
pydocstyle = {enabled = false}
autopep8 = {enabled = false}
yapf = {enabled = false}
flake8 = {enabled = false}
pylint = {enabled = false}
ruff = {enabled = true, extendSelect = ["I"]}
mypy = {enabled = true, live_mode = true, strict = true}
